version: '3'

services:
  fast-data-dev:
    ports:
      - "9092:9092"
      - "3030:3030"
      - "9581-9585:9581-9585"
    image: lensesio/fast-data-dev:3.6
    container_name: fast-data-dev
    # network_mode: "host"
    # environment:
    #   - ADV_HOST=[VM_EXTERNAL_IP]
    #   - RUNNING_SAMPLEDATA=1
